/**
 * @file l10n.js
 * @brief Gestion de la localisation (traduction) pour l'extension Questassure.
 * Fournit des dictionnaires anglais/français et des fonctions pour traduire les messages dynamiquement.
 */

const vscode = require('vscode');

/**
 * Dictionnaire de traduction contenant les clés et leurs valeurs associées
 * en anglais ('en') et en français ('fr').
 */
const translations = {
    en: {
        "formatter.failed": "Questassure formatter failed: {0}",
        "sim.no_active_editor": "No active editor open to run simulation.",
        "sim.select_tb": "Select the testbench entity to simulate",
        "sim.enter_tb_manual": "$(pencil) Enter testbench name manually...",
        "sim.prompt_tb_name": "Enter testbench entity name",
        "sim.placeholder_tb_name": "e.g., tb_counter",
        "sim.prompt_stop_time": "Simulation stop time",
        "sim.placeholder_stop_time": "e.g., 1us, 500ns, 10ms",
        "sim.prompt_work_lib": "VHDL work library",
        "sim.placeholder_work_lib": "e.g., work, my_lib",
        "sim.log.starting": "Starting simulation from project directory: {0}",
        "sim.log.tb": "Testbench: {0}",
        "sim.log.stop_time": "Stop Time: {0}",
        "sim.log.lib": "Library: {0}",
        "sim.log.compiling": "Compiling and running VHDL testbench...",
        "sim.progress.title": "Questassure: Simulating {0}",
        "sim.log.stdout_header": "\n--- STDOUT ---",
        "sim.log.stderr_header": "\n--- STDERR ---",
        "sim.log.success": "\n[SUCCESS] Simulation completed successfully.",
        "sim.log.waves": "[WAVES] Waveform file generated at: {0}",
        "sim.log.launching_surfer": "[LAUNCH] Launching Surfer via command: {0}",
        "sim.log.surfer_launch_warning": "[WARNING] Could not launch Surfer automatically: {0}",
        "sim.msg.surfer_failed": "Simulation successful! Waveform generated. (Could not launch Surfer automatically)",
        "sim.btn.copy_path": "Copy Wave Path",
        "sim.log.surfer_success": "[SUCCESS] Surfer launched successfully with waveform.",
        "sim.msg.surfer_success": "Simulation successful! Waveform opened in Surfer.",
        "sim.msg.success_no_waves": "Simulation completed successfully (no wave file generated).",
        "sim.log.failed": "\n[FAILED] Simulation failed with return code {0}.",
        "sim.msg.failed": "Simulation failed. Check the Questassure Simulation output channel.",
        "sim.log.run_failed": "\nFailed to run simulation: {0}",
        "sim.msg.run_failed": "Failed to run simulation.",
        "codeaction.compile_dep": "Compile Dependency: {0}",
        "codeaction.compile_dep_title": "Compile Dependency {0}",
        "rtl.no_active_editor": "Please open a VHDL file to view its RTL schematic.",
        "rtl.progress.extracting": "Questassure: Extracting RTL for {0}",
        "rtl.err.no_entity": "Could not find VHDL entity declaration in the file.",
        "rtl.err.failed": "Failed to extract RTL: {0}",
        "rtl.err.entity_not_found": "Could not find source file for component {0}.",
        "rtl.panel.title": "RTL / FSM Schematic: {0}",
        "rtl.export.success": "SVG successfully exported!",
        "rtl.export.error": "Failed to export SVG: {0}",
        "rtl.mermaid.success": "Mermaid diagram copied to clipboard!",
        "wave.panel.title": "Waveforms: {0}",
        "wave.preset.saved": "Waveform preset successfully saved!",
        "wave.preset.loaded": "Waveform preset successfully loaded!",
        "ghdl.err.not_available": "GHDL is not available in PATH. Please install GHDL first.",
        "yosys.err.not_available": "Yosys is not available in PATH. Please install Yosys first.",
        "ghdl.err.analysis_failed": "GHDL analysis failed for {0}: {1}",
        "ghdl.err.synthesis_failed": "GHDL synthesis failed: {0}",
        "yosys.err.synthesis_failed": "Yosys synthesis failed: {0}",
        "netlistsvg.err.failed": "netlistsvg failed to generate SVG: {0}",
        "netlistsvg.err.no_file": "SVG file was not generated by netlistsvg.",
        "project.err.dep_has_errors": "Dependency '{0}' at {1} has errors.",
        "project.err.not_vhdl": "Not a VHDL file: {0}",
        "svg.table.inputs": "Inputs",
        "svg.table.outputs": "Outputs",
        "svg.table.defaults": "Default values",
        "svg.legend.loopback": "* Implicit loopback: If no transition condition is met, the state remains unchanged."
    },
    fr: {
        "formatter.failed": "Le formateur Questassure a échoué : {0}",
        "sim.no_active_editor": "Aucun éditeur actif n'est ouvert pour lancer la simulation.",
        "sim.select_tb": "Sélectionnez l'entité de testbench à simuler",
        "sim.enter_tb_manual": "$(pencil) Saisir le nom du testbench manuellement...",
        "sim.prompt_tb_name": "Entrez le nom de l'entité de testbench",
        "sim.placeholder_tb_name": "ex: tb_counter",
        "sim.prompt_stop_time": "Temps d'arrêt de la simulation",
        "sim.placeholder_stop_time": "ex: 1us, 500ns, 10ms",
        "sim.prompt_work_lib": "Bibliothèque de travail VHDL",
        "sim.placeholder_work_lib": "ex: work, my_lib",
        "sim.log.starting": "Démarrage de la simulation depuis le dossier du projet : {0}",
        "sim.log.tb": "Testbench : {0}",
        "sim.log.stop_time": "Temps d'arrêt : {0}",
        "sim.log.lib": "Bibliothèque : {0}",
        "sim.log.compiling": "Compilation et exécution du testbench VHDL...",
        "sim.progress.title": "Questassure : Simulation de {0}",
        "sim.log.stdout_header": "\n--- STDOUT ---",
        "sim.log.stderr_header": "\n--- STDERR ---",
        "sim.log.success": "\n[SUCCESS] Simulation terminée avec succès.",
        "sim.log.waves": "[WAVES] Fichier de chronogramme généré à : {0}",
        "sim.log.launching_surfer": "[LAUNCH] Lancement de Surfer via la commande : {0}",
        "sim.log.surfer_launch_warning": "[WARNING] Impossible de lancer Surfer automatiquement : {0}",
        "sim.msg.surfer_failed": "Simulation réussie ! Ondes générées. (Impossible de lancer Surfer automatiquement)",
        "sim.btn.copy_path": "Copier le chemin des ondes",
        "sim.log.surfer_success": "[SUCCESS] Surfer lancé avec succès avec le fichier de chronogramme.",
        "sim.msg.surfer_success": "Simulation réussie ! Chronogramme ouvert dans Surfer.",
        "sim.msg.success_no_waves": "Simulation terminée avec succès (aucun fichier de chronogramme généré).",
        "sim.log.failed": "\n[FAILED] La simulation a échoué avec le code de retour {0}.",
        "sim.msg.failed": "La simulation a échoué. Vérifiez le canal de sortie Questassure Simulation.",
        "sim.log.run_failed": "\nImpossible de lancer la simulation : {0}",
        "sim.msg.run_failed": "Échec du lancement de la simulation.",
        "codeaction.compile_dep": "Compiler la dépendance : {0}",
        "codeaction.compile_dep_title": "Compiler la dépendance {0}",
        "rtl.no_active_editor": "Veuillez ouvrir un fichier VHDL pour afficher son schéma RTL.",
        "rtl.progress.extracting": "Questassure : Extraction du RTL pour {0}",
        "rtl.err.no_entity": "Impossible de trouver la déclaration de l'entité VHDL dans le fichier.",
        "rtl.err.failed": "Échec de l'extraction du RTL : {0}",
        "rtl.err.entity_not_found": "Impossible de trouver le fichier source pour le composant {0}.",
        "rtl.panel.title": "Schéma RTL / FSM : {0}",
        "rtl.export.success": "SVG exporté avec succès !",
        "rtl.export.error": "Échec de l'export du SVG : {0}",
        "rtl.mermaid.success": "Diagramme Mermaid copié dans le presse-papiers !",
        "wave.panel.title": "Chronogramme : {0}",
        "wave.preset.saved": "Configuration de chronogramme sauvegardée avec succès !",
        "wave.preset.loaded": "Configuration de chronogramme chargée avec succès !",
        "ghdl.err.not_available": "GHDL n'est pas disponible dans le PATH. Veuillez d'abord installer GHDL.",
        "yosys.err.not_available": "Yosys n'est pas disponible dans le PATH. Veuillez d'abord installer Yosys.",
        "ghdl.err.analysis_failed": "L'analyse GHDL a échoué pour {0} : {1}",
        "ghdl.err.synthesis_failed": "La synthèse GHDL a échoué : {0}",
        "yosys.err.synthesis_failed": "La synthèse Yosys a échoué : {0}",
        "netlistsvg.err.failed": "netlistsvg n'a pas pu générer le SVG : {0}",
        "netlistsvg.err.no_file": "Le fichier SVG n'a pas été généré par netlistsvg.",
        "project.err.dep_has_errors": "La dépendance '{0}' à {1} contient des erreurs.",
        "project.err.not_vhdl": "Ce n'est pas un fichier VHDL : {0}",
        "svg.table.inputs": "Entrées",
        "svg.table.outputs": "Sorties",
        "svg.table.defaults": "Valeurs par défaut",
        "svg.legend.loopback": "* Rebouclage implicite : Si aucune transition n'est active, l'état reste inchangé."
    }
};

/**
 * Récupère la langue (locale) courante de l'extension.
 * Vérifie d'abord la configuration de l'extension Questassure,
 * puis se rabat sur la langue de l'environnement VS Code.
 * 
 * @returns {string} Le code de langue détecté ('en' ou 'fr').
 */
function getLocale() {
    const config = vscode.workspace.getConfiguration('questassure');
    const langSetting = config.get('language') || 'auto';
    if (langSetting === 'en') {
        return 'en';
    }
    if (langSetting === 'fr') {
        return 'fr';
    }
    // Langue globale de VS Code
    const envLang = vscode.env.language || 'en';
    if (envLang.startsWith('fr')) {
        return 'fr';
    }
    return 'en';
}

/**
 * Traduit une clé de localisation en injectant des arguments dynamiques si fournis.
 * Si la clé n'est pas présente dans la langue sélectionnée, elle recherche dans la langue par défaut (anglais).
 *
 * @param {string} key - La clé de traduction souhaitée.
 * @param {...string} args - Les valeurs à injecter à la place des jetons {0}, {1}, etc.
 * @returns {string} Le texte traduit.
 */
function l(key, ...args) {
    const locale = getLocale();
    let text = (translations[locale] && translations[locale][key]) || translations['en'][key] || key;
    if (args.length > 0) {
        args.forEach((val, idx) => {
            text = text.replace(new RegExp(`\\{${idx}\\}`, 'g'), val);
        });
    }
    return text;
}

module.exports = {
    l,
    getLocale
};
